version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
      - ./init-minio.sh:/init-minio.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./data:/source-data
      - ./scripts:/scripts
    entrypoint: /scripts/setup-minio.sh

  image-processor:
    build:
      context: ./image-processor
      dockerfile: Dockerfile
    container_name: image-processor
    depends_on:
      - minio-init
    volumes:
      - ./data:/input
      - ./processed:/output
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: webapp
    ports:
      - "8080:80"
    depends_on:
      - image-processor

volumes:
  minio_data:
